### ISSUE TITLE
Config file allows the user to define init variables for any template treated.

### ISSUE THREAD

**Issue by arapelle** [arapelle/temgen#76]
``` toml
[variables]
var_name_1 = "value_name"
var_name_2 = "value_name"
```
